# Generated by Django 4.2.30 on 2026-05-20 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('description', models.TextField(verbose_name='상세 설명')),
                ('item_url', models.URLField(blank=True, verbose_name='상품 링크')),
                ('image', models.ImageField(blank=True, null=True, upload_to='buys/', verbose_name='상품 이미지')),
                ('buy_type', models.CharField(choices=[('bundle', '묶음 나눠사기'), ('min_order', '최소주문금액')], default='min_order', max_length=10, verbose_name='구매 방식')),
                ('total_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='총 수량')),
                ('target_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='목표 금액(원)')),
                ('unit_price', models.PositiveIntegerField(verbose_name='개당 가격(원)')),
                ('deadline', models.DateTimeField(verbose_name='모집 마감일')),
                ('status', models.CharField(choices=[('open', '모집 중'), ('matched', '매칭 완료'), ('cancelled', '취소됨'), ('expired', '기간 만료')], default='open', max_length=10, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_buys', to=settings.AUTH_USER_MODEL, verbose_name='개설자')),
            ],
            options={
                'verbose_name': '공동구매',
                'verbose_name_plural': '공동구매 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='수량')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group_buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='buys.groupbuy', verbose_name='공동구매')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL, verbose_name='참여자')),
            ],
            options={
                'verbose_name': '참여',
                'verbose_name_plural': '참여 목록',
                'unique_together': {('group_buy', 'user')},
            },
        ),
    ]
