# Generated by Django 4.2.30 on 2026-05-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupbuy',
            name='category',
            field=models.CharField(choices=[('식품', '식품'), ('생활용품', '생활용품'), ('도서', '도서'), ('디지털', '디지털'), ('택시', '택시'), ('해외직구', '해외직구'), ('정기결제', '정기결제'), ('기타', '기타')], default='기타', max_length=12, verbose_name='종류'),
        ),
        migrations.AddField(
            model_name='groupbuy',
            name='emoji',
            field=models.CharField(default='🛍️', max_length=16, verbose_name='대표 이모지'),
        ),
        migrations.AlterField(
            model_name='groupbuy',
            name='description',
            field=models.TextField(blank=True, verbose_name='상세 설명'),
        ),
    ]
