# Generated by Django 4.2.30 on 2026-05-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buys', '0002_groupbuy_category_groupbuy_emoji_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupbuy',
            name='buy_type',
            field=models.CharField(choices=[('bundle', '묶음 나눠사기'), ('min_order', '최소주문금액'), ('group_discount', '단체 할인 받기')], default='min_order', max_length=14, verbose_name='구매 방식'),
        ),
        migrations.AlterField(
            model_name='groupbuy',
            name='status',
            field=models.CharField(choices=[('open', '모집 중'), ('extending', '추가 모집 중'), ('matched', '매칭 완료'), ('done', '완료 처리'), ('cancelled', '취소됨'), ('expired', '기간 만료')], default='open', max_length=10, verbose_name='상태'),
        ),
    ]
