# Generated by Django 4.2.30 on 2026-05-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buys', '0003_alter_groupbuy_buy_type_alter_groupbuy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupbuy',
            name='buy_type',
            field=models.CharField(choices=[('bundle', '묶음 나눠사기'), ('min_order', '최소주문금액 모으기'), ('group_discount', '단체 할인 받기')], default='min_order', max_length=14, verbose_name='구매 방식'),
        ),
    ]
