# Generated by Django 4.2.30 on 2026-05-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buys', '0004_alter_groupbuy_buy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupbuy',
            name='preview_image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='링크 미리보기 이미지'),
        ),
    ]
